application/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from flask_migrate import Migrate
from werkzeug.security import generate_password_hash, check_password_hash


# database & migrations
migrate = Migrate()
db = SQLAlchemy()


class User(UserMixin, db.Model):
    """
    User authentication
    source: https://hackersandslackers.com/flask-login-user-authentication/
    """
    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(32))
    email = db.Column(db.String(32), unique=True, nullable=False)
    password = db.Column(db.String(128), nullable=False)

    def set_password(self, password):
        """
        Used during registration
        """
        self.password = generate_password_hash(password, method='sha256')

    def check_password(self, password):
        """
        Used on login
        """
        return check_password_hash(self.password, password)

application/file/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileField, FileRequired, FileAllowed
from wtforms import SubmitField


class UploadForm(FlaskForm):
    photo = FileField(validators=[
        FileRequired(), FileAllowed(['jpg', 'png'], 'Jpg or png images only')])
    submit = SubmitField('Upload')

application/__init__.py
from flask import Flask
from .auth import routes as auth_routes
from .auth.routes import login_manager
from .file import routes as file_routes
from .models import db, migrate, User


def create_app():
    """
    Application factory.

    Returns:
        app(flask.app.Flask)
    """
    app = Flask(__name__, instance_relative_config=True)

    # configuration files (2nd: private & inside instance folder)
    app.config.from_object('application.config')
    app.config.from_pyfile('config.py')

    # register blueprints
    app.register_blueprint(auth_routes.auth_bp, url_prefix='/auth')
    app.register_blueprint(file_routes.file_bp, url_prefix='/file')

    # intialize extensions (database, migration, auth)
    db.init_app(app)
    migrate.init_app(app, db)
    login_manager.init_app(app, db)

    return app

application/file/routes.py
from flask import Blueprint, render_template, url_for, redirect
from flask import current_app as app
from .forms import UploadForm
from werkzeug.utils import secure_filename
import os


file_bp = Blueprint('file', __name__,
                    template_folder='templates', static_folder='static')


@file_bp.route('/upload', methods=['GET', 'POST'])
def upload():
    form = UploadForm()

    if form.validate_on_submit():
        # get file from form
        f = form.photo.data
        filename = secure_filename(f.filename)

        # save file inside instance folder
        f.save(os.path.join(app.instance_path, 'photos', filename))

        return redirect(url_for('.success'))

    return render_template('file/upload.html', form=form)


@file_bp.route('/success')
def success():
    return render_template('file/success.html')

application/templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Flask Web Application</title>
    </head>

    <body>
        <header>
            {% include 'nav.html' %}
        </header>

        <main>
            {% block content %}
            {% endblock %}
        </main>
    </body>
</html>

application/templates/nav.html
<nav>
    <ul>
        <li><a href="{{ url_for('file.upload') }}">Upload</a></li>
        {% if current_user.is_authenticated %}
            <li><a href="{{ url_for('auth.profile') }}">Profile</a></li>
            <li><a href="{{ url_for('auth.logout') }}">Logout</a></li>
        {% else %}
            <li><a href="{{ url_for('auth.login') }}">Login</a></li>
            <li><a href="{{ url_for('auth.register') }}">Register</a></li>
        {% endif %}
    </ul>
</nav>